<?php

namespace App\Http\Requests;

use App\Student;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class StudentPost extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        $id = $this->route('id');
        return [
            'name' => ['required', 'string', Rule::unique('student')->ignore($id), 'max:255'],
            'age' => 'required|integer',
            'sex' => ['required', Rule::in([Student::UNKNOWN, Student::MAN, Student::WOMAN])]
        ];
    }

    /**
     * 自定义错误信息
     * @return array
     * user: trina
     */
    public function messages()
    {
        return [
            'required' => ':attribute不能为空',
            'integer' => ':attribute必须为整数',
            'string' => ':attribute必须为字符串',
            'unique' => '该:attribute已被使用',
            'max' => ':attribute的长度不能超过：max',
            'in' => ':attribute必须是以下值之一：:values'
        ]; // TODO: Change the autogenerated stub
    }

    /**
     * 自定义属性名
     * @return array
     * user: trina
     */
    public function attributes()
    {
        return [
            'name' => '姓名',
            'age' => '年龄',
            'sex' => '性别',
        ]; // TODO: Change the autogenerated stub
    }
}
